default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: councilman_management_development

test:
  <<: *default
  database: councilman_management_test

production:
  <<: *default
  database: councilman_management_production
  username: councilman_management
  password: <%= ENV['COUNCILMAN_MANAGEMENT_DATABASE_PASSWORD'] %>
