default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: db
  port: <%= ENV['DATABASE_PORT'] %>

development:
  <<: *default
  database: councilman_management_development

test:
  <<: *default
  database: councilman_management_test

production:
  <<: *default
  database: councilman_management_production
  username: councilman_management
  password: <%= ENV['COUNCILMAN_MANAGEMENT_DATABASE_PASSWORD'] %>
